# Generated by Django 6.0.6 on 2026-06-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_count",
            field=models.IntegerField(default=0),
        ),
    ]
