# Generated by Django 6.0.6 on 2026-06-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_completed_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="last_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
